# Generated by Django 4.2.7 on 2025-07-22 05:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="CompanyNews",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("news_title", models.CharField(max_length=500)),
                ("news_date", models.DateField()),
                (
                    "news_image",
                    models.ImageField(blank=True, null=True, upload_to="news_images/"),
                ),
                ("news_body", models.TextField()),
                ("news_summary", models.TextField(blank=True, null=True)),
                (
                    "news_category",
                    models.CharField(
                        choices=[
                            ("Financial", "Financial"),
                            ("Business", "Business"),
                            ("Technology", "Technology"),
                            ("Environment", "Environment"),
                            ("Corporate", "Corporate"),
                            ("Awards", "Awards"),
                            ("Partnership", "Partnership"),
                            ("Expansion", "Expansion"),
                            ("Other", "Other"),
                        ],
                        default="Other",
                        max_length=100,
                    ),
                ),
                ("is_featured", models.BooleanField(default=False)),
                ("views_count", models.IntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Company News",
                "verbose_name_plural": "Company News",
                "db_table": "company_news",
                "ordering": ["-news_date", "-created_at"],
            },
        ),
        migrations.CreateModel(
            name="CompanyProfile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("company_name", models.CharField(max_length=255)),
                ("stock_symbol", models.CharField(max_length=10, unique=True)),
                (
                    "company_logo",
                    models.ImageField(
                        blank=True, null=True, upload_to="company_logos/"
                    ),
                ),
                ("established_year", models.IntegerField(blank=True, null=True)),
                (
                    "company_type",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                ("sector", models.CharField(blank=True, max_length=100, null=True)),
                ("industry", models.CharField(blank=True, max_length=100, null=True)),
                (
                    "headquarters",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("total_employees", models.IntegerField(blank=True, null=True)),
                (
                    "market_cap",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=15, null=True
                    ),
                ),
                (
                    "paid_up_capital",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=15, null=True
                    ),
                ),
                (
                    "authorized_capital",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=15, null=True
                    ),
                ),
                (
                    "current_share_price",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=10, null=True
                    ),
                ),
                ("total_shares", models.BigIntegerField(blank=True, null=True)),
                ("listed_shares", models.BigIntegerField(blank=True, null=True)),
                ("website_url", models.URLField(blank=True, null=True)),
                ("email", models.EmailField(blank=True, max_length=254, null=True)),
                ("phone", models.CharField(blank=True, max_length=50, null=True)),
                (
                    "chairman_name",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("ceo_name", models.CharField(blank=True, max_length=255, null=True)),
                ("company_description", models.TextField(blank=True, null=True)),
                ("key_products", models.TextField(blank=True, null=True)),
                (
                    "production_capacity",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("plant_locations", models.TextField(blank=True, null=True)),
                ("vision_statement", models.TextField(blank=True, null=True)),
                ("mission_statement", models.TextField(blank=True, null=True)),
                ("core_values", models.TextField(blank=True, null=True)),
                (
                    "financial_year",
                    models.CharField(blank=True, max_length=20, null=True),
                ),
                (
                    "annual_revenue",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=15, null=True
                    ),
                ),
                (
                    "net_profit",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=15, null=True
                    ),
                ),
                (
                    "eps",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=10, null=True
                    ),
                ),
                (
                    "book_value",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=10, null=True
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Company Profile",
                "verbose_name_plural": "Company Profiles",
                "db_table": "company_profile",
            },
        ),
    ]
