# Generated by Django 4.2.7 on 2025-07-22 06:21

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Company",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        default="Sarbottam Cement Limited", max_length=200
                    ),
                ),
                ("symbol", models.CharField(default="SARBTM", max_length=10)),
                (
                    "sector",
                    models.CharField(
                        default="Manufacturing and Processing", max_length=100
                    ),
                ),
                ("founded_year", models.IntegerField(blank=True, null=True)),
                (
                    "headquarters",
                    models.CharField(
                        default="Sunwal, Nawalparasi, State-5, Nepal", max_length=200
                    ),
                ),
                (
                    "company_type",
                    models.CharField(default="Public Company", max_length=50),
                ),
                (
                    "employees",
                    models.CharField(default="501-1,000 employees", max_length=50),
                ),
                (
                    "description",
                    models.TextField(
                        default="An innovator and pioneer of the cement industry of Nepal, Sarbottam Cement Pvt. Ltd. (SCPL) is the first and only cement manufacturers to use a completely European production line."
                    ),
                ),
                (
                    "website",
                    models.URLField(
                        default="https://saurabhgroup.com/sarbottam-cement"
                    ),
                ),
                ("email", models.EmailField(blank=True, max_length=254, null=True)),
                ("phone", models.CharField(blank=True, max_length=50, null=True)),
                (
                    "market_price",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=10, null=True
                    ),
                ),
                (
                    "market_cap",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=15, null=True
                    ),
                ),
                (
                    "pe_ratio",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=10, null=True
                    ),
                ),
                (
                    "dividend_yield",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=5, null=True
                    ),
                ),
                ("listed_shares", models.BigIntegerField(blank=True, null=True)),
                (
                    "paid_up_capital",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=15, null=True
                    ),
                ),
                (
                    "book_value",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=10, null=True
                    ),
                ),
                (
                    "parent_group",
                    models.CharField(default="Saurabh Group", max_length=100),
                ),
                (
                    "industry_position",
                    models.TextField(
                        default="First and only cement manufacturer to use completely European production line in Nepal"
                    ),
                ),
                (
                    "logo",
                    models.ImageField(
                        blank=True, null=True, upload_to="company_logos/"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Company",
                "verbose_name_plural": "Companies",
            },
        ),
        migrations.CreateModel(
            name="CompanyNews",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("news_title", models.CharField(max_length=300)),
                ("news_date", models.DateTimeField(default=django.utils.timezone.now)),
                (
                    "news_image",
                    models.ImageField(blank=True, null=True, upload_to="news_images/"),
                ),
                ("news_body", models.TextField()),
                ("is_featured", models.BooleanField(default=False)),
                ("is_published", models.BooleanField(default=True)),
                ("source", models.CharField(blank=True, max_length=100, null=True)),
                ("author", models.CharField(blank=True, max_length=100, null=True)),
                (
                    "meta_description",
                    models.CharField(blank=True, max_length=160, null=True),
                ),
                ("slug", models.SlugField(blank=True, null=True, unique=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "company",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="news",
                        to="sarbottam.company",
                    ),
                ),
            ],
            options={
                "verbose_name": "Company News",
                "verbose_name_plural": "Company News",
                "ordering": ["-news_date"],
            },
        ),
        migrations.CreateModel(
            name="CompanyFinancial",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("fiscal_year", models.CharField(max_length=20)),
                ("quarter", models.CharField(blank=True, max_length=10, null=True)),
                (
                    "revenue",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=15, null=True
                    ),
                ),
                (
                    "net_profit",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=15, null=True
                    ),
                ),
                (
                    "eps",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=10, null=True
                    ),
                ),
                (
                    "total_assets",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=15, null=True
                    ),
                ),
                (
                    "total_equity",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=15, null=True
                    ),
                ),
                ("report_date", models.DateField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "company",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="financials",
                        to="sarbottam.company",
                    ),
                ),
            ],
            options={
                "verbose_name": "Financial Data",
                "verbose_name_plural": "Financial Data",
                "ordering": ["-report_date"],
            },
        ),
        migrations.CreateModel(
            name="CompanyAchievement",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                ("description", models.TextField()),
                ("achievement_date", models.DateField()),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("award", "Award"),
                            ("certification", "Certification"),
                            ("milestone", "Milestone"),
                            ("recognition", "Recognition"),
                            ("expansion", "Business Expansion"),
                        ],
                        max_length=100,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "company",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="achievements",
                        to="sarbottam.company",
                    ),
                ),
            ],
            options={
                "verbose_name": "Company Achievement",
                "verbose_name_plural": "Company Achievements",
                "ordering": ["-achievement_date"],
            },
        ),
    ]
