# Generated by Django 4.2.7 on 2025-07-22 07:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("sarbottam", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="companyfinancial",
            old_name="eps",
            new_name="earnings_per_share",
        ),
        migrations.RenameField(
            model_name="companyfinancial",
            old_name="net_profit",
            new_name="net_income",
        ),
        migrations.RenameField(
            model_name="companyfinancial",
            old_name="fiscal_year",
            new_name="report_period",
        ),
        migrations.RenameField(
            model_name="companyfinancial",
            old_name="revenue",
            new_name="shareholders_equity",
        ),
        migrations.RenameField(
            model_name="companyfinancial",
            old_name="total_equity",
            new_name="total_liabilities",
        ),
        migrations.RenameField(
            model_name="companynews",
            old_name="author",
            new_name="category",
        ),
        migrations.RemoveField(
            model_name="company",
            name="industry_position",
        ),
        migrations.RemoveField(
            model_name="company",
            name="listed_shares",
        ),
        migrations.RemoveField(
            model_name="company",
            name="logo",
        ),
        migrations.RemoveField(
            model_name="company",
            name="paid_up_capital",
        ),
        migrations.RemoveField(
            model_name="company",
            name="parent_group",
        ),
        migrations.RemoveField(
            model_name="companyfinancial",
            name="quarter",
        ),
        migrations.RemoveField(
            model_name="companynews",
            name="meta_description",
        ),
        migrations.RemoveField(
            model_name="companynews",
            name="source",
        ),
        migrations.AddField(
            model_name="company",
            name="annual_revenue",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="company",
            name="net_profit",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="company",
            name="production_capacity",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="company",
            name="roe",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=5, null=True
            ),
        ),
        migrations.AddField(
            model_name="company",
            name="total_assets",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="companyfinancial",
            name="report_file",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="companyfinancial",
            name="total_revenue",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=15, null=True
            ),
        ),
        migrations.AddField(
            model_name="companynews",
            name="summary",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="company",
            name="description",
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name="company",
            name="market_cap",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name="companyachievement",
            name="category",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name="companynews",
            name="news_image",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name="companynews",
            name="slug",
            field=models.CharField(blank=True, max_length=100, null=True, unique=True),
        ),
        migrations.CreateModel(
            name="PriceHistory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField()),
                ("open_price", models.DecimalField(decimal_places=2, max_digits=10)),
                ("high_price", models.DecimalField(decimal_places=2, max_digits=10)),
                ("low_price", models.DecimalField(decimal_places=2, max_digits=10)),
                ("close_price", models.DecimalField(decimal_places=2, max_digits=10)),
                (
                    "percentage_change",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=8, null=True
                    ),
                ),
                ("volume", models.BigIntegerField(blank=True, null=True)),
                (
                    "turnover",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=15, null=True
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "company",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="price_history",
                        to="sarbottam.company",
                    ),
                ),
            ],
            options={
                "verbose_name": "Price History",
                "verbose_name_plural": "Price History",
                "ordering": ["-date"],
                "unique_together": {("company", "date")},
            },
        ),
    ]
